server:
   port: 8082
   
spring:
  application:
      name: TICKET-BOOKING-SERVICE
  zipkin:
      base-url:  http://127.0.0.1:9411/
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
       default-zone: http://localhost:8761/eureka/
  instance:
     hostname: localhost